use_frameworks!

target '01_Example' do
  pod '01', :path => '../'

  target '01_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
